[config]
  skip_core_tasks = true

[tasks.default]
  dependencies = ["benchmarks"]

[tasks.benchmarks]
  command = "node"
  args    = ["src/index.mjs"]

[tasks.lint]
  command = "eslint"
  args    = ["--cache", "--ext", ".mjs", "src"]

[tasks."lint:fix"]
  command = "eslint"
  args    = ["--cache", "--fix", "--ext", ".mjs", "src"]

[tasks.format]
  command = "prettier"
  args    = ["-w", "src"]

[tasks.verify]
  dependencies = ["format", "lint", "benchmarks"]
