[config]
  skip_core_tasks = true

[env]
  TARGET = { script = ["rustc -vV | sed -n 's|host: ||p'"] }

[tasks.default]
  dependencies = ["test"]

[tasks.build]
  dependencies = ["release", "debug"]

[tasks.test]
  env          = { VARIANT = "rust" }
  dependencies = ["build"]
  command      = "node"
  args         = ["--test", "../reference.js"]

[tasks.release]
  script = [
    "cargo build --target ${TARGET} --target-dir ../../tmp/references/rust/targets/release --release",
    "mkdir -p ../../tmp/references/rust/release",
    "cp ../../tmp/references/rust/targets/release/${TARGET}/release/readme ../../tmp/references/rust/release/",
    "cp ../../tmp/references/rust/targets/release/${TARGET}/release/reference ../../tmp/references/rust/release/",
  ]

[tasks.debug]
  script = [
    "cargo build --target ${TARGET} --target-dir ../../tmp/references/rust/targets/debug",
    "mkdir -p ../../tmp/references/rust/debug",
    "cp ../../tmp/references/rust/targets/debug/${TARGET}/debug/readme ../../tmp/references/rust/debug/",
    "cp ../../tmp/references/rust/targets/debug/${TARGET}/debug/reference ../../tmp/references/rust/debug/",
  ]
