[config]
  skip_core_tasks = true

[env]
  TARGET = { script = ["rustc -vV | sed -n 's|host: ||p'"] }

[tasks.default]
  dependencies = ["build"]

[tasks.build]
  dependencies = ["prepare", "release", "debug"]

[tasks.test]
  command = "node"
  args    = ["--test", "../reference.test.mjs"]

[tasks.lint]
  command = "cargo"
  args    = ["clippy"]

[tasks."lint:fix"]
  command = "cargo"
  args    = ["clippy", "--fix", "--allow-dirty"]

[tasks.format]
  command = "cargo"
  args    = ["fmt"]

[tasks.clean]
  command = "cargo"
  args    = ["clean"]

[tasks.verify]
  dependencies = ["format", "lint", "clean", "build", "test", "readme"]

[tasks.readme]
  command = "cargo"
  args    = ["run", "--bin", "readme"]

[tasks.prepare]
  script = [
    "mkdir -p dist",
    "rm -rf dist/*",
    "ln -s ../target/release/reference dist/reference-release",
    "ln -s ../target/debug/reference dist/reference-debug",
  ]

[tasks.release]
  command = "cargo"
  args = [
    "build",
    "-Z",
    "unstable-options",
    "--target",
    "${TARGET}",
    "--release",
    "--artifact-dir",
    "target/release",
  ]

[tasks.debug]
  command = "cargo"
  args = [
    "build",
    "-Z",
    "unstable-options",
    "--target",
    "${TARGET}",
    "--artifact-dir",
    "target/debug",
  ]
