[config]
  skip_core_tasks = true

[env]
  TARGET = { script = ["rustc -vV | sed -n 's|host: ||p'"] }

[tasks.default]
  dependencies = ["build"]

[tasks.build]
  dependencies = ["cpp", "wasm"]

[tasks.test]
  cwd     = "../test-utils"
  command = "cargo"
  args    = ["test"]

[tasks.lint]
  command = "cargo"
  args    = ["clippy"]

[tasks."lint:tools"]
  cwd     = "./tools"
  command = "eslint"
  args    = ["--cache", "--ext", ".mjs", "."]

[tasks."lint:tools:fix"]
  cwd     = "./tools"
  command = "eslint"
  args    = ["--cache", "--fix", "--ext", ".mjs", "src"]

[tasks."lint:fix"]
  command = "cargo"
  args    = ["clippy", "--fix", "--allow-dirty"]

[tasks.format]
  command = "cargo"
  args    = ["fmt"]

[tasks."format:tools"]
  cwd     = "./tools"
  command = "prettier"
  args    = ["-w", "../src/wasm", "."]

[tasks.clean]
  run_task = { name = ["cargo-clean", "dist-clean"] }

[tasks.verify]
  dependencies = [
    "format",
    "format:tools",
    "lint",
    "lint:tools",
    "clean",
    "build",
    "test",
  ]

[tasks.publish]
  dependencies = ["wasm-release"]
  command      = "node"
  args         = ["./tools/publish.mjs"]

[tasks.cpp]
  dependencies = ["cpp-headers", "cpp-libs"]

[tasks.cpp-libs]
  dependencies = ["cpp-release", "cpp-debug"]

[tasks.cpp-release]
  env      = { CONFIGURATION = "release", "CARGO_OPTIONS" = "--release", POSTBUILD_OPTIONS = "DEBUG:false" }
  run_task = "cpp-lib"

[tasks.cpp-debug]
  env      = { CONFIGURATION = "debug", "CARGO_OPTIONS" = "", POSTBUILD_OPTIONS = "DEBUG:true" }
  run_task = "cpp-lib"

[tasks.cpp-lib]
  script = [
    "mkdir -p dist/cpp/${CONFIGURATION}",
    "rm -rf dist/cpp/${CONFIGURATION}/*",
    "cargo build -Z unstable-options --target ${TARGET} ${CARGO_OPTIONS} --out-dir target/cpp/${CONFIGURATION}",
    "cp target/cpp/${CONFIGURATION}/libmilo.a target/headers/milo.h dist/cpp/${CONFIGURATION}",
    "node ./tools/postbuild-cpp.mjs	${CONFIGURATION} ${POSTBUILD_OPTIONS}",
  ]

[tasks.cpp-headers]
  command = "cbindgen"
  args    = ["--quiet", "--output", "target/headers/milo.h"]

[tasks.wasm]
  dependencies = ["wasm-release", "wasm-debug"]

[tasks.wasm-release]
  env      = { CONFIGURATION = "release", "CARGO_OPTIONS" = "--release", "WASMPACK_OPTIONS" = "--release", POSTBUILD_OPTIONS = "DEBUG:false" }
  run_task = "wasm-module"

[tasks.wasm-debug]
  env      = { CONFIGURATION = "debug", "CARGO_OPTIONS" = "", "WASMPACK_OPTIONS" = "--debug", POSTBUILD_OPTIONS = "DEBUG:true" }
  run_task = "wasm-module"

[tasks.wasm-module]
  script = [
    "mkdir -p dist/wasm",
    "rm -rf dist/wasm/${CONFIGURATION}",
    "mkdir -p dist/wasm/${CONFIGURATION}",
    "cargo build -Z unstable-options --target wasm32-unknown-unknown ${CARGO_OPTIONS}",
    "cp -a target/wasm32-unknown-unknown/${CONFIGURATION}/milo.wasm dist/wasm/${CONFIGURATION}",
    "wasm-opt -O3 -o dist/wasm/${CONFIGURATION}/milo.wasm dist/wasm/${CONFIGURATION}/milo.wasm",
    "node ./tools/postbuild-wasm.mjs	${CONFIGURATION} ${POSTBUILD_OPTIONS}",
  ]

[tasks.cargo-clean]
  command = "cargo"
  args    = ["clean"]

[tasks.dist-clean]
  command = "rm"
  args    = ["-r", "-f", "dist"]
