[config]
  skip_core_tasks = true

[env]
  TARGET = { script = ["rustc -vV | sed -n 's|host: ||p'"] }

[tasks.default]
  dependencies = ["build"]

[tasks.build]
  dependencies = ["cpp", "wasm"]

[tasks.test]
  command = "cargo"
  args    = ["test"]

[tasks.lint]
  command = "cargo"
  args    = ["clippy"]

[tasks."lint:tools"]
  cwd     = "./tools"
  command = "eslint"
  args    = ["--cache", "--ext", ".js", "."]

[tasks."lint:tools:fix"]
  cwd     = "./tools"
  command = "eslint"
  args    = ["--cache", "--fix", "--ext", ".js", "src"]

[tasks."lint:fix"]
  command = "cargo"
  args    = ["clippy", "--fix", "--allow-dirty"]

[tasks.format]
  command = "cargo"
  args    = ["fmt"]

[tasks."format:tools"]
  cwd     = "./tools"
  command = "prettier"
  args    = ["-w", "../src/wasm", "."]

[tasks.clean]
  run_task = { name = ["cargo-clean", "dist-clean"] }

[tasks.verify]
  dependencies = [
    "format",
    "format:tools",
    "lint",
    "lint:tools",
    "clean",
    "build",
    "test",
  ]

[tasks.publish]
  dependencies = ["wasm-release"]
  command      = "node"
  args         = ["./tools/publish.js"]

[tasks.cpp]
  dependencies = ["cpp:headers", "cpp:libs"]

[tasks."cpp:libs"]
  dependencies = ["cpp:release", "cpp:debug"]

[tasks."cpp:release"]
  env      = { CONFIGURATION = "release", "CARGO_OPTIONS" = "--release", POSTBUILD_OPTIONS = "DEBUG:false" }
  run_task = "cpp:lib"

[tasks."cpp:debug"]
  env      = { CONFIGURATION = "debug", "CARGO_OPTIONS" = "--release --features debug", POSTBUILD_OPTIONS = "DEBUG:true" }
  run_task = "cpp:lib"

[tasks."cpp:lib"]
  script = [
    "mkdir -p dist/cpp/${CONFIGURATION}",
    "rm -rf dist/cpp/${CONFIGURATION}/*",
    "cargo build -Z unstable-options --target ${TARGET} ${CARGO_OPTIONS} --artifact-dir target/cpp/${CONFIGURATION}",
    "cp target/cpp/${CONFIGURATION}/libmilo.a target/headers/milo.h dist/cpp/${CONFIGURATION}",
    "node ./tools/postbuild-cpp.js	${CONFIGURATION} ${POSTBUILD_OPTIONS}",
  ]

[tasks."cpp:headers"]
  command = "cbindgen"
  args    = ["--quiet", "--output", "target/headers/milo.h"]

[tasks.wasm]
  dependencies = ["wasm:release", "wasm:debug"]

[tasks."wasm:release"]
  env      = { CONFIGURATION = "release", "CARGO_OPTIONS" = "--release", "WASMPACK_OPTIONS" = "--release", POSTBUILD_OPTIONS = "DEBUG:false" }
  run_task = "wasm:module"

[tasks."wasm:debug"]
  env      = { CONFIGURATION = "debug", "CARGO_OPTIONS" = "--release --features debug", "WASMPACK_OPTIONS" = "--release", POSTBUILD_OPTIONS = "DEBUG:true" }
  run_task = "wasm:module"

[tasks."wasm:module"]
  script = [
    "mkdir -p dist/wasm",
    "rm -rf dist/wasm/${CONFIGURATION}",
    "mkdir -p dist/wasm/${CONFIGURATION}",
    "RUSTFLAGS=\"-C target-feature=+simd128\" cargo build -Z unstable-options --target wasm32-unknown-unknown ${CARGO_OPTIONS}",
    "cp -a target/wasm32-unknown-unknown/release/milo.wasm dist/wasm/${CONFIGURATION}",
    "wasm-opt -O3 --enable-bulk-memory-opt --enable-simd -o dist/wasm/${CONFIGURATION}/milo.wasm dist/wasm/${CONFIGURATION}/milo.wasm",
    "node ./tools/postbuild-wasm.js	${CONFIGURATION} ${POSTBUILD_OPTIONS}",
  ]

[tasks.distclean]
  command = "rm"
  args    = ["-r", "-f", "dist"]

[tasks."llhttp:import"]
  script = ["node tools/import-llhttp-tests.js ${1} ."]

[tasks."llhttp:review"]
  script = ["cargo run --example llhttp -- --review ${1}"]

[tasks."llhttp:show"]
  script = ["cargo run --example llhttp -- --show ${1}"]

[tasks."llhttp:update"]
  script = ["cargo run --example llhttp -- --update ${1}"]
