[config]
  skip_core_tasks = true

[tasks.default]
  dependencies = ["test"]

[tasks.build]
  dependencies = ["milo"]

[tasks.test]
  env          = { VARIANT = "wasm" }
  dependencies = ["build"]
  command      = "node"
  args         = ["--test", "../reference.js"]

# This is purposely not included in test, it is meant for manual run
[tasks.simple]
  dependencies = ["build"]
  command      = "node"
  args         = ["./src/simple.js"]

# This is purposely not included in test, it is meant for manual run
[tasks.callbacks]
  dependencies = ["build"]
  command      = "node"
  args         = ["./src/callbacks.js"]

[tasks."milo"]
  cwd     = "../../parser"
  command = "makers"
  args    = ["wasm"]
