name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  ci:
    name: Sanity Check
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use supported Rust version
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rustfmt, clippy, rust-src
      - name: Add Rust targets
        run: rustup target add wasm32-unknown-unknown
      - name: Use supported Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 26
      - name: Install system dependencies
        run: |
          curl -sSL -o binaryen.tar.gz https://github.com/WebAssembly/binaryen/releases/download/version_123/binaryen-version_123-x86_64-linux.tar.gz 
          tar -xzf binaryen.tar.gz
          echo "$PWD/binaryen-version_123/bin" >> "$GITHUB_PATH"
          $PWD/binaryen-version_123/bin/wasm-opt --version
      - name: Restore cached dependencies (Cargo)
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            parser/target
            macros/target
            tmp/reference/rust/targets
          key: cargo-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Restore cached dependencies (PNPM)
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: node-modules-${{ hashFiles('package.json') }}
      - name: Install makers
        uses: taiki-e/cache-cargo-install-action@v3
        with:
          tool: cargo-make
      - name: Install cbindgen
        uses: taiki-e/cache-cargo-install-action@v3
        with:
          tool: cbindgen
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: makers build
      - name: Format
        run: makers format
      - name: Lint
        run: makers lint
      - name: Test
        run: makers test
      - name: References
        run: makers references
